#! /bin/sh

sxhkd &
compton -b
synclient TouchpadOff=1

$HOME/.config/polybar/launch.sh

xbacklight 15
amixer set Master 10%
amixer set Master mute

bspc monitor -d term web code IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          20
bspc config top_padding         25
bspc config left_padding        5
bspc config right_padding       5
bspc config bottom_padding      5

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
bspc config pointer_follows_focus   false
bspc config click_to_focus          true
bspc confic ignore_ewmh_focus       true 

bspc config remove_disabled_monitors true 
bspc config remove_unplugged_monitors true

bspc config normal_border_color '#282a36'
bspc config focused_border_color '#527fc1'
bspc config presel_feedback_color '#7b7bbc'

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a jetbrains-idea desktop='^3'
bspc rule -a termite -o desktop=focused
bspc rule -a Termite:ranger state=floating
